
name: Run Sync Federated Engine

dataset_path: ./Data
dataset: cifar100

model:
  arch: tnt+patch16+224
  pretrain: /home/jericho/Project/federated-meta-learning/Data/models/tnt_s_patch16_224.pth

param:
  seed: 1402
  rounds: 9
  n_classes: 100
  alpha: 0.1
  epochs: 10
  batch_size: 4
  lr: 0.001
  img_size: 224

server:
  device: gpu

client1:
  device: gpu

client2:
  device: gpu


client3:
  device: gpu


client4:
  device: gpu


client5:
  device: gpu

client6:
  device: gpu

client7:
  device: gpu


client8:
  device: gpu


client9:
  device: gpu


client10:
  device: gpu
